-- Create the department table
CREATE TABLE department (
    DEPT_ID_SK INT NOT NULL,
    DEPT_ID INT NOT NULL,
    DEPT_NAME VARCHAR(50) NULL,
    FROM_DTTM DATE NULL,
    TO_DTTM DATE NULL,
    RETIRED_FLAG INT NULL,
    PRIMARY KEY (DEPT_ID_SK)
);

-- Create the employee table
CREATE TABLE employee (
    EMP_ID_SK INT NOT NULL,
    EMP_ID INT NOT NULL,
    FIRST_NAME VARCHAR(50) NULL,
    LAST_NAME VARCHAR(50) NULL,
    DEPT_ID INT NULL,
    MANAGER_ID INT NULL,
    OFFICE_ID INT NULL,
    FROM_DTTM DATE NULL,
    TO_DTTM DATE NULL,
    PRIMARY KEY (EMP_ID_SK)
);

-- Create the office table
CREATE TABLE office (
    OFFICE_ID_SK INT NOT NULL,
    OFFICE_ID INT NOT NULL,
    ZIP INT NULL,
    DEPT_ID INT NULL,
    FROM_DTTM DATE NULL,
    TO_DTTM DATE NULL,
    PRIMARY KEY (OFFICE_ID_SK)
);